name: Build

on:
  push:
    branches:
      - "**"
    tags:
      - '**'
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'

    - name: Build with Gradle Wrapper
      run: ./gradlew build
